[workspace]
resolver = "2"
members = [
    "sysdeps",
    "fdevent",
    "adb-types",
    "adb_io",
    "trace",
    "rust-adb-pairing-auth",
    "adb-sockets",
    "socket-spec",
    "adb-utils",
    "adb-auth",
    "adb-protocol",
    "adb-transport",
    "adb-services",
    "adb-listeners",
    "adb-usb",
    "adb-mdns",
    "adb-daemon",
    "rust-adb", "adb-pairing", "adb-fastdeploy",
]

[workspace.lints.rust]
missing_docs = "deny"
