[package]
name = "adb-services"
version = "0.1.0"
edition = "2021"

[dependencies]
adb-protocol = { path = "../adb-protocol" }
adb-transport = { path = "../adb-transport" }
adb-sockets = { path = "../adb-sockets" }
adb-utils = { path = "../adb-utils" }
adb-types = { path = "../adb-types" }
adb_io = { path = "../adb_io" }
sysdeps = { path = "../sysdeps" }
fdevent = { path = "../fdevent" }
adb-socket-spec = { path = "../socket-spec" }
adb-mdns = { path = "../adb-mdns" }
adb-listeners = { path = "../adb-listeners" }
anyhow = "1.0"
log = "0.4.20"
libc = "0.2"
nix = { version = "0.27", features = ["term", "fs", "process", "net", "socket", "uio"] }
regex = "1.10"
mio = { version = "0.8", features = ["net", "os-poll"] }
bytes = "1.5.0"
prost = "0.13"
zerocopy = { version = "0.8.38", features = ["derive"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0", features = [
    "Win32_System_Console",
    "Win32_System_Threading",
    "Win32_System_Pipes",
    "Win32_Foundation",
    "Win32_Security"
] }


[dev-dependencies]
env_logger = "0.10.0"
tempfile = "3.8"

[lints]
workspace = true
