[package]
name = "adb-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
libc = "0.2"
rust-adb-crypto = { path = "../crypto" }
adb-types = { path = "../adb-types" }
adb-utils = { path = "../adb-utils" }
adb_io = { path = "../adb_io" }
base64 = "0.21"
log = "0.4"
lazy_static = "1.4"
rand = "0.8"
rsa = "0.9"
sha1 = "0.10"
hostname = "0.3"

[dev-dependencies]
tempfile = "3.3"

[lints]
workspace = true
